version: '3'
services:
  db:
    image: postgres:16.0
    container_name: postgres-16.0-container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: 
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5500:5500"
  demo-web:
    build: .
    command: "./bin/rails server"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER_TEST=${POSTGRES_USER_TEST}
      - POSTGRES_PASSWORD_TEST=${POSTGRES_PASSWORD_TEST}
      - POSTGRES_USER_DEV=${POSTGRES_USER_DEV}
      - POSTGRES_PASSWORD_DEV=${POSTGRES_PASSWORD_DEV}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db
    ports:
      - "3000:3000"
volumes:
  postgres_data: {}
  app-storage: {}